{% set name = "robosample" %}
{% set version = "0.1.0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  path: ..   # build from local repo (relative to recipe/). Alternatively use git_url & git_rev.

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake
    - ninja
    - pkg-config
    - python=3.12
    - blas
    - lapack
  host:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake
    - ninja
    - pkg-config
    - python=3.12
    - blas
    - lapack
  run:
    - python=3.12
    - blas
    - lapack
    - numpy
    - scipy
    - pandas
    - matplotlib
    - mdtraj
    - ambertools
    - parmed
    - rdkit
    - astropy
    - networkx
    - tqdm

about:
  home: "https://your.repo/url"
  license: "BSD-3-Clause"
  summary: "RoboSample C++/pybind11 Python bindings"

#test:
#  requires:
#    - python
#  commands:
#    - bash ./recipe/run_test.sh

# conda mambabuild recipe --channel omnia --channel salilab --channel conda-forge --channel defaults
# conda install --use-local robosample

# conda mambabuild --output recipe
