[default.extend-identifiers]
nax = "nax"
BA = "BA"
ANG = "ANG"
parm = "parm"
nd = "nd"
ND1 = "ND1"
ND2 = "ND2"
SER = "SER"
THR = "THR"
OLT = "OLT"
OG = "OG"
OG1 = "OG1"
conect = "conect"
CONECT = "CONECT"
equil = "equil"
EQUIL = "EQUIL"
pople = "pople"

[default.extend-words]
nax = "nax"
BA = "BA"
ANG = "ANG"
parm = "parm"
nd = "nd"
ND1 = "ND1"
ND2 = "ND2"
SER = "SER"
THR = "THR"
OLT = "OLT"
OG = "OG"
OG1 = "OG1"
conect = "conect"
CONECT = "CONECT"
equil = "equil"
EQUIL = "EQUIL"
pople = "pople"
