// ============================================================================
//  TestJointKernels.cpp -- the per-mobilizer PRIMITIVES. These are the
//  Robosample analogue of Simbody's per-RigidBodyNodeSpec checks: for each
//  JointType we verify the q/u sizing, the cross-mobilizer transform X_FM(q),
//  and -- the load-bearing one -- that X_FM, the velocity Jacobian H_FM, and the
//  q-dot (N) map are mutually consistent, by finite-differencing X_FM along a
//  trajectory generated by the q-dot map and comparing the resulting spatial
//  velocity to H_FM*u. The same idea finite-differences H_FM itself against
//  HDot_FM. This is exactly the consistency Simbody's framework guarantees
//  implicitly, here pinned down directly on the bare kernels (no engine, no
//  forcefield) -- and it certifies the BendStretch / SphericalCoords / FreeLine
//  HDot terms that previously carried only a "needs golden test" comment.
// ============================================================================
#include <array>
#include <gtest/gtest.h>

#include "JointKernels.hpp"
#include "RobotModel.hpp"
#include "TestHelpers.hpp"

using namespace robo;
using rtest::Rng;

namespace {

constexpr std::array<JointType, 10> kAllJoints = {
    JointType::Rigid,       JointType::Torsion,      JointType::Slider,   JointType::Cylinder,
    JointType::BendStretch, JointType::Cartesian,    JointType::Ball,     JointType::SphericalCoords,
    JointType::FreeLine,    JointType::Free};

const char* name(JointType jt) {
    switch (jt) {
        case JointType::Rigid: return "Rigid";
        case JointType::Torsion: return "Torsion";
        case JointType::Slider: return "Slider";
        case JointType::Cylinder: return "Cylinder";
        case JointType::BendStretch: return "BendStretch";
        case JointType::Cartesian: return "Cartesian";
        case JointType::Ball: return "Ball";
        case JointType::SphericalCoords: return "SphericalCoords";
        case JointType::FreeLine: return "FreeLine";
        case JointType::Free: return "Free";
    }
    return "?";
}

// angular velocity in F from a central difference of the rotation:
// dR_FM/dt = [w_FM]x R_FM  =>  [w]x = Rdot R^T  (w expressed in F).
Vec3 angVelFromRotationFD(const Rotation& Rp, const Rotation& Rm, Real h) {
    const Mat33 Rdot = (Rp - Rm) * (Real(1) / (Real(2) * h));
    const Mat33 W = Rdot * Rp.transpose();
    const Mat33 W2 = Rdot * Rm.transpose(); // average reduces the O(h^2) bias
    return Vec3(Real(0.5) * (W(2, 1) + W2(2, 1)),
                Real(0.5) * (W(0, 2) + W2(0, 2)),
                Real(0.5) * (W(1, 0) + W2(1, 0)));
}

// The joint's q-dot map qdot = N(q) u (same N the engine's calcQDot uses), so we
// can evolve q(t) = q0 + t*qdot0 for the finite difference.
void jointQDot(JointType jt, const Real* q, const Real* u, Real* qdot) {
    if (jt == JointType::Ball) {
        const Vec4 quat(q[0], q[1], q[2], q[3]);
        const Vec4 qd = Rotation::convertAngVelToQuaternionDot(quat, Vec3(u[0], u[1], u[2]));
        for (int k = 0; k < 4; ++k) qdot[k] = qd[k];
        return;
    }
    if (jt == JointType::Free) {
        const Vec4 quat(q[0], q[1], q[2], q[3]);
        const Vec4 qd = Rotation::convertAngVelToQuaternionDot(quat, Vec3(u[0], u[1], u[2]));
        for (int k = 0; k < 4; ++k) qdot[k] = qd[k];
        qdot[4] = u[3]; qdot[5] = u[4]; qdot[6] = u[5];
        return;
    }
    if (jt == JointType::FreeLine) {
        const Vec4 quat(q[0], q[1], q[2], q[3]);
        const Rotation R = jointX_FM(jt, q, 0).R();
        const Vec3 wF = R * Vec3(u[0], u[1], 0);
        const Vec4 qd = Rotation::convertAngVelToQuaternionDot(quat, wF);
        for (int k = 0; k < 4; ++k) qdot[k] = qd[k];
        qdot[4] = u[2]; qdot[5] = u[3]; qdot[6] = u[4];
        return;
    }
    const int nu = RobotModel::jointNU(jt);
    for (int j = 0; j < nu; ++j) qdot[j] = u[j]; // QDotIsAlwaysTheSameAsU
}

// q(t) = q0 + t*qdot0, renormalizing any quaternion block.
std::array<Real, 7> evolveQ(JointType jt, const Real* q0, const Real* qdot0, Real t) {
    std::array<Real, 7> q{};
    const int nq = RobotModel::jointNQ(jt);
    for (int i = 0; i < nq; ++i) q[i] = q0[i] + t * qdot0[i];
    if (RobotModel::jointUsesQuaternion(jt)) {
        const Real n = std::sqrt(q[0] * q[0] + q[1] * q[1] + q[2] * q[2] + q[3] * q[3]);
        for (int k = 0; k < 4; ++k) q[k] /= n;
    }
    return q;
}

std::array<Real, 7> randomQ(JointType jt, Rng& rng) {
    std::array<Real, 7> q{};
    const int nq = RobotModel::jointNQ(jt);
    for (int i = 0; i < nq; ++i) q[i] = rng.uniform(-1.3, 1.3);
    if (RobotModel::jointUsesQuaternion(jt)) {
        const auto quat = rng.unitQuat();
        for (int k = 0; k < 4; ++k) q[k] = quat.elems[k];
    }
    return q;
}

} // namespace

// ---------------------------------------------------------------------------
//  P1: q/u sizing and joint-fact truth tables (the single source of truth).
// ---------------------------------------------------------------------------
TEST(JointFacts, DofAndNqTable) {
    struct Row { JointType jt; int nu; int nq; bool quat; };
    const Row rows[] = {
        {JointType::Rigid, 0, 0, false},       {JointType::Torsion, 1, 1, false},
        {JointType::Slider, 1, 1, false},      {JointType::Cylinder, 2, 2, false},
        {JointType::BendStretch, 2, 2, false}, {JointType::Cartesian, 3, 3, false},
        {JointType::Ball, 3, 4, true},         {JointType::SphericalCoords, 3, 3, false},
        {JointType::FreeLine, 5, 7, true},     {JointType::Free, 6, 7, true},
    };
    for (const auto& r : rows) {
        EXPECT_EQ(RobotModel::jointNU(r.jt), r.nu) << name(r.jt);
        EXPECT_EQ(RobotModel::jointNQ(r.jt), r.nq) << name(r.jt);
        EXPECT_EQ(RobotModel::jointUsesQuaternion(r.jt), r.quat) << name(r.jt);
        // Non-quaternion joints store nq == nu. Quaternion joints inflate the
        // orientation block 3->4, so nq = nu + (#quaternion-encoded rot dofs not
        // in u): +1 for Ball/Free, +2 for FreeLine (only 2 of its 3 quaternion-
        // borne rotational dofs are mobilities).
        if (!r.quat) EXPECT_EQ(r.nq, r.nu) << name(r.jt);
        else EXPECT_GT(r.nq, r.nu) << name(r.jt);
    }
}

TEST(JointFacts, FlexibleAndLegalRoot) {
    EXPECT_FALSE(RobotModel::jointIsFlexible(JointType::Rigid));
    for (auto jt : kAllJoints)
        if (jt != JointType::Rigid) EXPECT_TRUE(RobotModel::jointIsFlexible(jt)) << name(jt);

    const JointType legal[] = {JointType::Free, JointType::Cartesian, JointType::Rigid,
                               JointType::FreeLine, JointType::Ball, JointType::Torsion};
    const JointType illegal[] = {JointType::Slider, JointType::Cylinder,
                                 JointType::BendStretch, JointType::SphericalCoords};
    for (auto jt : legal) EXPECT_TRUE(RobotModel::jointIsLegalRoot(jt)) << name(jt);
    for (auto jt : illegal) EXPECT_FALSE(RobotModel::jointIsLegalRoot(jt)) << name(jt);
}

TEST(JointFacts, ConstantHFMClassification) {
    for (auto jt : {JointType::Rigid, JointType::Torsion, JointType::Slider, JointType::Cylinder,
                    JointType::Cartesian, JointType::Ball, JointType::Free})
        EXPECT_TRUE(RobotModel::jointHasConstantHFM(jt)) << name(jt);
    for (auto jt : {JointType::BendStretch, JointType::SphericalCoords, JointType::FreeLine})
        EXPECT_FALSE(RobotModel::jointHasConstantHFM(jt)) << name(jt);
}

// ---------------------------------------------------------------------------
//  P2: analytic X_FM spot checks.
// ---------------------------------------------------------------------------
TEST(JointXFM, AnalyticSpotChecks) {
    EXPECT_TRUE(rtest::NearMat33(jointX_FM(JointType::Rigid, nullptr, 0).R(), Mat33(Real(1)), rtest::kTight));

    {
        Real q[1] = {Real(0.7)};
        const Transform X = jointX_FM(JointType::Torsion, q, 0);
        Rotation Rz; Rz.setRotationFromAngleAboutZ(Real(0.7));
        EXPECT_TRUE(rtest::NearMat33(X.R(), Rz, rtest::kTight));
        EXPECT_TRUE(rtest::NearVec3(X.p(), Vec3(0), rtest::kTight));
    }
    {
        Real q[1] = {Real(1.25)};
        const Transform X = jointX_FM(JointType::Slider, q, 0);
        EXPECT_TRUE(rtest::NearMat33(X.R(), Mat33(Real(1)), rtest::kTight));
        EXPECT_TRUE(rtest::NearVec3(X.p(), Vec3(Real(1.25), 0, 0), rtest::kTight));
    }
    {
        Real q[3] = {Real(0.3), Real(-0.4), Real(0.9)};
        const Transform X = jointX_FM(JointType::Cartesian, q, 0);
        EXPECT_TRUE(rtest::NearMat33(X.R(), Mat33(Real(1)), rtest::kTight));
        EXPECT_TRUE(rtest::NearVec3(X.p(), Vec3(Real(0.3), Real(-0.4), Real(0.9)), rtest::kTight));
    }
    {
        Real q[2] = {Real(0.5), Real(2.0)};
        const Transform X = jointX_FM(JointType::Cylinder, q, 0);
        Rotation Rz; Rz.setRotationFromAngleAboutZ(Real(0.5));
        EXPECT_TRUE(rtest::NearMat33(X.R(), Rz, rtest::kTight));
        EXPECT_TRUE(rtest::NearVec3(X.p(), Vec3(0, 0, Real(2.0)), rtest::kTight));
    }
    {
        Real q[7] = {1, 0, 0, 0, 0, 0, 0};
        EXPECT_TRUE(rtest::NearMat33(jointX_FM(JointType::Ball, q, 0).R(), Mat33(Real(1)), rtest::kTight));
        const Transform Xf = jointX_FM(JointType::Free, q, 0);
        EXPECT_TRUE(rtest::NearMat33(Xf.R(), Mat33(Real(1)), rtest::kTight));
        EXPECT_TRUE(rtest::NearVec3(Xf.p(), Vec3(0), rtest::kTight));
    }
    {
        // SphericalCoords (Z-radial), az=ze=0 -> M origin at radius along +Z.
        Real q[3] = {0, 0, Real(1.7)};
        const Transform X = jointX_FM(JointType::SphericalCoords, q, 0);
        EXPECT_TRUE(rtest::NearVec3(X.p(), Vec3(0, 0, Real(1.7)), rtest::kAlg));
    }
    {
        Real q[7] = {1, 0, 0, 0, Real(0.2), Real(-0.6), Real(0.8)};
        const Transform X = jointX_FM(JointType::FreeLine, q, 0);
        EXPECT_TRUE(rtest::NearMat33(X.R(), Mat33(Real(1)), rtest::kTight));
        EXPECT_TRUE(rtest::NearVec3(X.p(), Vec3(Real(0.2), Real(-0.6), Real(0.8)), rtest::kTight));
    }
}

// ---------------------------------------------------------------------------
//  P3: X_FM / H_FM / N(q) mutual consistency for EVERY joint.
//      V_FM := H_FM(q)*u  must equal  d/dt X_FM along q(t)=q0+t*N(q0)u.
// ---------------------------------------------------------------------------
TEST(JointJacobian, HFMisDerivativeOfXFM) {
    Rng rng(0xA11CE5);
    const Real h = 1e-6;
    for (auto jt : kAllJoints) {
        const int nu = RobotModel::jointNU(jt);
        if (nu == 0) continue; // Rigid: nothing to differentiate
        for (int trial = 0; trial < 200; ++trial) {
            const auto q0 = randomQ(jt, rng);
            std::array<Real, 6> u{};
            for (int j = 0; j < nu; ++j) u[j] = rng.gaussian(0, Real(0.6));

            std::array<Real, 7> qdot0{};
            jointQDot(jt, q0.data(), u.data(), qdot0.data());

            const auto qp = evolveQ(jt, q0.data(), qdot0.data(), +h);
            const auto qm = evolveQ(jt, q0.data(), qdot0.data(), -h);
            const Transform Xp = jointX_FM(jt, qp.data(), 0);
            const Transform Xm = jointX_FM(jt, qm.data(), 0);

            const Vec3 w_fd = angVelFromRotationFD(Xp.R(), Xm.R(), h);
            const Vec3 v_fd = (Xp.p() - Xm.p()) * (Real(1) / (Real(2) * h));

            const Transform X0 = jointX_FM(jt, q0.data(), 0);
            std::array<SpatialVec, 6> H{};
            jointH_FM(jt, X0, H.data());
            Vec3 w_an(0), v_an(0);
            for (int j = 0; j < nu; ++j) {
                w_an = w_an + H[j][0] * u[j];
                v_an = v_an + H[j][1] * u[j];
            }
            ASSERT_TRUE(rtest::NearVec3(w_an, w_fd, 1e-4)) << name(jt) << " angular trial " << trial;
            ASSERT_TRUE(rtest::NearVec3(v_an, v_fd, 1e-4)) << name(jt) << " linear trial " << trial;
        }
    }
}

// ---------------------------------------------------------------------------
//  P4: HDot_FM consistency. d/dt H_FM(q(t)) (FD) must equal jointHDot_FM with
//      velocity argument V_FM = H_FM*u. Zero for the constant-H joints; nonzero
//      and correct for BendStretch / SphericalCoords / FreeLine. This is the
//      check that retires the "golden-test before trust" caveat.
// ---------------------------------------------------------------------------
TEST(JointJacobianDot, HDotMatchesDerivativeOfHFM) {
    Rng rng(0xBEEF11);
    const Real h = 1e-6;
    for (auto jt : kAllJoints) {
        const int nu = RobotModel::jointNU(jt);
        if (nu == 0) continue;
        for (int trial = 0; trial < 150; ++trial) {
            const auto q0 = randomQ(jt, rng);
            std::array<Real, 6> u{};
            for (int j = 0; j < nu; ++j) u[j] = rng.gaussian(0, Real(0.6));
            std::array<Real, 7> qdot0{};
            jointQDot(jt, q0.data(), u.data(), qdot0.data());

            const Transform X0 = jointX_FM(jt, q0.data(), 0);
            std::array<SpatialVec, 6> H0{};
            jointH_FM(jt, X0, H0.data());
            Vec3 w0(0), v0(0);
            for (int j = 0; j < nu; ++j) { w0 = w0 + H0[j][0] * u[j]; v0 = v0 + H0[j][1] * u[j]; }
            const SpatialVec V_FM(w0, v0);

            std::array<SpatialVec, 6> Hdot{};
            jointHDot_FM(jt, X0, V_FM, Hdot.data());

            const auto qp = evolveQ(jt, q0.data(), qdot0.data(), +h);
            const auto qm = evolveQ(jt, q0.data(), qdot0.data(), -h);
            std::array<SpatialVec, 6> Hp{}, Hm{};
            jointH_FM(jt, jointX_FM(jt, qp.data(), 0), Hp.data());
            jointH_FM(jt, jointX_FM(jt, qm.data(), 0), Hm.data());

            for (int j = 0; j < nu; ++j) {
                const Vec3 dAng = (Hp[j][0] - Hm[j][0]) * (Real(1) / (Real(2) * h));
                const Vec3 dLin = (Hp[j][1] - Hm[j][1]) * (Real(1) / (Real(2) * h));
                ASSERT_TRUE(rtest::NearVec3(Hdot[j][0], dAng, 1e-4))
                    << name(jt) << " HDot ang col " << j << " trial " << trial;
                ASSERT_TRUE(rtest::NearVec3(Hdot[j][1], dLin, 1e-4))
                    << name(jt) << " HDot lin col " << j << " trial " << trial;
            }
        }
    }
}

// ---------------------------------------------------------------------------
//  P5: the Ball-quaternion regression. A Ball body is a 3-dof pure rotation
//  (q = unit quaternion, no translation) -- the exact behaviour the old engine
//  mishandled (it gave Ball nq=nu=0 and never renormalized). P1/P3 cover the
//  sizing and rate; this pins "rotation only, no translation" explicitly.
// ---------------------------------------------------------------------------
TEST(BallRegression, PureRotationNoTranslation) {
    Rng rng(0x5A11);
    for (int t = 0; t < 50; ++t) {
        const auto quat = rng.unitQuat();
        Real q[4] = {quat.elems[0], quat.elems[1], quat.elems[2], quat.elems[3]};
        const Transform X = jointX_FM(JointType::Ball, q, 0);
        // M origin coincides with F origin: no translation dof.
        EXPECT_TRUE(rtest::NearVec3(X.p(), Vec3(0), rtest::kTight));
        // X_FM.R() is a proper rotation: R R^T = I, det +1 (orthonormality check).
        const Mat33 RRt = X.R() * X.R().transpose();
        EXPECT_TRUE(rtest::NearMat33(RRt, Mat33(Real(1)), rtest::kAlg));
        // H_FM is the identity rotational triple, no linear rows.
        std::array<SpatialVec, 3> H{};
        jointH_FM(JointType::Ball, X, H.data());
        EXPECT_TRUE(rtest::NearVec3(H[0][0], Vec3(1, 0, 0), rtest::kTight));
        EXPECT_TRUE(rtest::NearVec3(H[1][0], Vec3(0, 1, 0), rtest::kTight));
        EXPECT_TRUE(rtest::NearVec3(H[2][0], Vec3(0, 0, 1), rtest::kTight));
        EXPECT_TRUE(rtest::NearVec3(H[0][1], Vec3(0), rtest::kTight));
        EXPECT_TRUE(rtest::NearVec3(H[1][1], Vec3(0), rtest::kTight));
        EXPECT_TRUE(rtest::NearVec3(H[2][1], Vec3(0), rtest::kTight));
    }
}
