AMBER_FF19SB_ATOM_TYPES = {
    'C' : 'sp2 C carbonyl group',
    'CA': 'sp2 C pure aromatic (benzene)',
    'CB': 'sp2 aromatic C, 5&6 membered ring junction',
    'CC': 'sp2 aromatic C, 5 memb. ring HIS',
    'CD': 'sp2 C atom in the middle of: C=CD-CD=C',
    'CI': 'parmbsc0',
    'CK': 'sp2 C 5 memb.ring in purines (dA,dG)',
    'CP': 'sp2 C 5 memb.ring in purines (G)',
    'CM': 'sp2 C  pyrimidines in pos. 5 & 6 (dT,dC)',
    'CS': 'sp2 C  pyrimidines in pos. 5 & 6 (U)',
    'CN': 'sp2 C aromatic 5&6 memb.ring junct.(TRP)',
    'CQ': 'sp2 C in 5 mem.ring of purines between 2 N',
    'CR': 'sp2 arom as CQ but in HIS',
    'CT': 'sp3 aliphatic C',
    'CV': 'sp2 arom. 5 memb.ring w/1 N and 1 H (HIS)',
    'CW': 'sp2 arom. 5 memb.ring w/1 N-H and 1 H (HIS)',
    'C*': 'sp2 arom. 5 memb.ring w/1 subst. (TRP)',
    'CX': 'protein C-alpha (new to ff10)',
    'XC': 'protein C-alpha (new to ff19)',
    'CY': 'nitrile C (Howard et al.JCC,16,243,1995)',
    'CZ': 'sp C (Howard et al.JCC,16,243,1995)',
    'C5': 'sp2 C 5 memb.ring in purines (A)',
    'C4': 'sp2 C  pyrimidines in pos. 5 & 6 (C)',
    'C0': 'calcium',
    'H' : 'H bonded to nitrogen atoms',
    'HC': 'H aliph. bond. to C without electrwd.group',
    'H1': 'H aliph. bond. to C with 1 electrwd. group',
    'H2': 'H aliph. bond. to C with 2 electrwd.groups',
    'H3': 'H aliph. bond. to C with 3 eletrwd.groups',
    'HA': 'H arom. bond. to C without elctrwd. groups',
    'H4': 'H arom. bond. to C with 1 electrwd. group',
    'H5': 'H arom.at C with 2 elctrwd. gr,+HCOO group',
    'HO': 'hydroxyl group',
    'HS': 'hydrogen bonded to sulphur (pol?)',
    'HW': 'H in TIP3P water',
    'HP': 'H bonded to C next to positively charged gr',
    'HZ': 'H bond sp C (Howard et al.JCC,16,243,1995)',
    'F' : 'fluorine (not fluoride!)',
    'Cl': 'chlorine  (Applequist) (not chloride!)',
    'Br': 'bromine  (Applequist) (not bromide!)',
    'I' : 'iodine   (Applequist) (not iodide!)',
    'MG': 'magnesium',
    'N' : 'sp2 nitrogen in amide groups',
    'NA': 'sp2 N in 5 memb.ring w/H atom (HIS)',
    'NB': 'sp2 N in 5 memb.ring w/LP (HIS,ADE,GUA)',
    'NC': 'sp2 N in 6 memb.ring w/LP (ADE,GUA)',
    'N2': 'sp2 N in amino groups',
    'N3': 'sp3 N for charged amino groups (Lys, etc)',
    'NT': 'sp3 N for amino groups amino groups',
    'N*': 'sp2 N',
    'NY': 'nitrile N (Howard et al.JCC,16,243,1995)',
    'O' : 'carbonyl group oxygen',
    'O2': 'carboxyl and phosphate group oxygen',
    'OW': 'oxygen in TIP3P water',
    'OH': 'oxygen in hydroxyl group',
    'OS': 'ether and ester oxygen',
    'OP': '2- phosphate oxygen',
    'P' : 'phosphate,pol:JACS,112,8543,90,K.J.Miller',
    'S' : 'S in disulfide linkage,pol:JPC,102,2399,98',
    'SH': 'S in cystine',
    'CU': 'copper',
    'FE': 'iron',
    'Zn': 'Zn2+',
    'EP': 'extra point',
}

AMBER_GLYCAM_06_H_ATOM_TYPES = {
    'Cg': 'sp3 C aliphatic',
    'CT': 'sp3 C aliphatic',
    '2C': 'sp3 aliphatic C with two (duo) heavy atoms copied from ff12SB',
    '3C': 'sp3 aliphatic C with three (tres) heavy atoms copied from ff12SB',
    'CX': 'protein C-alpha (new to ff10)  copied from parm10',
    'Cy': 'sp3 C aliphatic - for sialic acid only!',
    'C ': 'sp2 C carbonyl group',
    'Cp': 'sp3 C aliphatic - carbon atom bonded to an oxygen atom bonded to a phosphorus atom',
    'Ck': 'sp2 C alkenes',
    'Cj': 'sp2 C alkenes for adjacent double bonds',
    'H ': 'H Bonded to nitrogen atoms',
    'H1': 'H aliph. bond. to C with 1 electrwd. groups',
    'H2': 'H aliph. bond. to C with 2 electrwd. groups',
    'Hc': 'H aliph. bond. to C without electrwd. groups',
    'Ha': 'H aliph. bond. to C in alkenes eg Ck',
    'Ho': 'H hydroxyl group',
    'HW': 'H TIP3P water',
    'Hp': 'H bonded to C next to positively charged group',
    'Ng': 'sp2 N amide group',
    'NT': 'sp3 N amine group',
    'N3': 'sp3 N for charged amino groups (Lys, phospholipids, etc)',
    'O ': 'O carbonyl group',
    'O2': 'O carboxyl group',
    'Oh': 'O hydroxyl group',
    'Os': 'O ether',
    'Oy': 'O ether - for sialic acid only!',
    'OW': 'O TIP3P water',
    'S ': 'sulphur in sulphates',
    'Sm': 'sulfane carbohydrate linkage (-CH2-S-CH2-)',
    'P ': 'phosphate in phosphates',
}

AMBER_GAFF2_ATOM_TYPES = {
    'c' : 'Sp2 C carbonyl group',
    'cs': 'Sp2 C in c=S',
    'c1': 'Sp C',
    'c2': 'Sp2 C',
    'c3': 'Sp3 C',
    'ca': 'Sp2 C in pure aromatic systems',
    'cp': 'Head Sp2 C that connect two rings in biphenyl sys.',
    'cq': 'Head Sp2 C that connect two rings in biphenyl sys. identical to cp',
    'cc': 'Sp2 carbons in non-pure aromatic systems',
    'cd': 'Sp2 carbons in non-pure aromatic systems, identical to cc',
    'ce': 'Inner Sp2 carbons in conjugated systems',
    'cf': 'Inner Sp2 carbons in conjugated systems, identical to ce',
    'cg': 'Inner Sp carbons in conjugated systems',
    'ch': 'Inner Sp carbons in conjugated systems, identical to cg',
    'cx': 'Sp3 carbons in triangle systems',
    'cy': 'Sp3 carbons in square systems',
    'c5': 'Sp3 carbons in five-memberred rings',
    'c6': 'Sp3 carbons in six-memberred rings',
    'cu': 'Sp2 carbons in triangle systems',
    'cv': 'Sp2 carbons in square systems',
    'cz': 'Sp2 carbon in guanidine group',
    'h1': 'H bonded to aliphatic carbon with 1 electrwd. group',
    'h2': 'H bonded to aliphatic carbon with 2 electrwd. group',
    'h3': 'H bonded to aliphatic carbon with 3 electrwd. group',
    'h4': 'H bonded to non-sp3 carbon with 1 electrwd. group',
    'h5': 'H bonded to non-sp3 carbon with 2 electrwd. group',
    'ha': 'H bonded to aromatic carbon',
    'hc': 'H bonded to aliphatic carbon without electrwd. group',
    'hn': 'H bonded to nitrogen atoms',
    'ho': 'Hydroxyl group',
    'hp': 'H bonded to phosphate',
    'hs': 'Hydrogen bonded to sulphur',
    'hw': 'Hydrogen in water',
    'hx': 'H bonded to C next to positively charged group',
    'f' : 'Fluorine',
    'cl': 'Chlorine',
    'br': 'Bromine',
    'i' : 'Iodine',
    'n' : 'Sp2 nitrogen in amide groups',
    'n1': 'Sp N',
    'n2': 'aliphatic Sp2 N with two connected atoms',
    'n3': 'Sp3 N with three connected atoms',
    'n4': 'Sp3 N with four connected atoms',
    'na': 'Sp2 N with three connected atoms',
    'nb': 'Sp2 N in pure aromatic systems',
    'nc': 'Sp2 N in non-pure aromatic systems',
    'nd': 'Sp2 N in non-pure aromatic systems, identical to nc',
    'ne': 'Inner Sp2 N in conjugated systems',
    'nf': 'Inner Sp2 N in conjugated systems, identical to ne',
    'nh': 'Amine N connected one or more aromatic rings',
    'no': 'Nitro N',
    'ns': 'amind N, with 1 attached hydrogen atom',
    'nt': 'amide N, with 2 attached hydrogen atoms',
    'nx': 'like n4, but only has one hydrogen atom',
    'ny': 'like n4, but only has two hydrogen atoms',
    'nz': 'like n4, but only has three three hydrogen atoms',
    'n+': 'NH4+',
    'nu': 'like nh, but only has one attached hydrogen atom',
    'nv': 'like nh, but only has two attached hydrogen atoms',
    'n7': 'like n3, but only has one attached hydrogen atom',
    'n8': 'like n3, but only has two attached hydrogen atoms',
    'n9': 'NH3',
    'ni': 'like n in RG3',
    'nj': 'like n in RG4',
    'nk': 'like n4/nx/ny in RG3',
    'nl': 'like n4/nx/ny in RG4',
    'nm': 'like nh in RG3',
    'nn': 'like nh in RG4',
    'np': 'like n3 in RG3',
    'nq': 'like n3 in RG4',
    'n5': 'like n7 in RG3',
    'n6': 'like n7 in RG4',
    'o' : 'Oxygen with one connected atom',
    'oh': 'Oxygen in hydroxyl group',
    'op': 'Oxygen in RG3',
    'oq': 'Oxygen in RG4',
    'os': 'Ether and ester oxygen',
    'ow': 'Oxygen in water',
    'p2': 'Phosphate with two connected atoms',
    'p3': 'Phosphate with three connected atoms, such as PH3',
    'p4': 'Phosphate with three connected atoms, such as O=P(CH3)2',
    'p5': 'Phosphate with four connected atoms, such as O=P(OH)3',
    'pb': 'Sp2 P in pure aromatic systems',
    'pc': 'Sp2 P in non-pure aromatic systems',
    'pd': 'Sp2 P in non-pure aromatic systems, identical to pc',
    'pe': 'Inner Sp2 P in conjugated systems',
    'pf': 'Inner Sp2 P in conjugated systems, identical to pe',
    'px': 'Special p4 in conjugated systems',
    'py': 'Special p5 in conjugated systems',
    's' : 'S with one connected atom',
    's2': 'S with two connected atom, involved at least one double bond',
    's4': 'S with three connected atoms',
    's6': 'S with four connected atoms',
    'sh': 'Sp3 S connected with hydrogen',
    'ss': 'Sp3 S in thio-ester and thio-ether',
    'sx': 'Special s4 in conjugated systems',
    'sy': 'Special s6 in conjugated systems',
    'sp': 'not described',
    'sq': 'not described'
}
