name: robo_base
channels:
  - conda-forge
  - nodefaults
dependencies:
  # Build tools
  - cmake
  - ninja
  - pkg-config
  - gcc_linux-64
  - gxx_linux-64

  # Python
  - python=3.12
  - pip

  # Coding tools
  - gtest

  # Hardware acceleration requested and installed by OpenMM
  # This happens regardless of the underlying hardware
  - ocl-icd
  - ocl-icd-system
  - opencl-headers
  - clinfo
  - rocm-core

  # OpenMP support for GNU and LLVM compilers
  - libgomp

  # Bioinformatics
  - openmm
  - openmmtools
  - parmed
  - mdtraj
  - mdanalysis
  - dacase::ambertools-dac=26
  - salilab::modeller
  - rdkit
  - pymol-open-source

  # Scientific computing and data analysis
  - numpy
  - scipy
  - astropy
  - networkx
  - tqdm
  - hypothesis
  - pandas
  - matplotlib
  - seaborn

  # Pip packages
  - pip:
    - conda-merge
    - pybind11-stubgen
    - pytest
    - pytest-xdist
    - pytest-cov
    - conda-merge
    - gcovr
    - coverage
    - anybadge
    - nox
    - pre-commit
    - clang-tidy
    - clang-format
    - cmake-format
    - scikit-build-core
    - python-louvain
    - openbabel-wheel
    - rcsbsearchapi
    - pdb2pqr
